Invercasa.Web/Models/DiasVacaciones.cs
using System.ComponentModel.DataAnnotations;

namespace Invercasa.Web.Models
{
    public class DiasVacaciones
    {
        [Required(ErrorMessage = "El campo Fecha Inicio es obligatorio.")]
        [DataType(DataType.Date)]
        public DateTime FechaInicio { get; set; }
        [Required(ErrorMessage = "El campo Fecha Fin es obligatorio.")]
        [DataType(DataType.Date)]
        public DateTime FechaFin { get; set; }
    }
}

Invercasa.Web/Models/ErrorViewModel.cs
namespace Invercasa.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Invercasa.Web/Controllers/EmpleadoController.cs
using Invercasa.AccesoDatos.AccesoDatos;
using Invercasa.Dominio.Entidades;
using Invercasa.Servicios.CasoUso;
using Invercasa.Servicios.Modelos;
using Invercasa.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace Invercasa.Web.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly ICalcularVacaciones _calcularVacaciones;
        private readonly ICrearEmpleado _crearEmpleado;
        private readonly IMostrarEmpleado _mostrarEmpleado;
        private readonly IRegistrarVacaciones _registrarVacaciones;
        private readonly IGenerarReporte _generarReporte;

        public EmpleadoController(ICalcularVacaciones calcularVacaciones, ICrearEmpleado crearEmpleado, IMostrarEmpleado mostrarEmpleado, IRegistrarVacaciones registrarVacaciones, IGenerarReporte generarReporte)
        {
            _calcularVacaciones = calcularVacaciones;
            _crearEmpleado = crearEmpleado;
            _mostrarEmpleado = mostrarEmpleado;
            _registrarVacaciones = registrarVacaciones;
            _generarReporte = generarReporte;
        }

        public ActionResult Index()
        {
            var result = _mostrarEmpleado.Mostrar();
            if (result == null)
            {
                return View();
            }
            else
            {
                return View(result);
            }

        }

        // GET: EmpleadoController/Create
        public ActionResult CrearEmpleado()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        // POST: EmpleadoController/Create
        public ActionResult CrearEmpleado(Empleado empleado)
        {
            empleado.ValidarNIdentidad = _crearEmpleado.ValidarCedula(empleado.NumeroIdentificacion);

            _crearEmpleado.Registrar(empleado);

            if (empleado.ValidarNIdentidad.Equals("No"))
            {
                ViewBag.Message = empleado.NumeroIdentificacion;
                return View();
            }
            else
                return RedirectToAction(nameof(Index));
        }

        public ActionResult Reporte(int id)
        {
            var result = _generarReporte.Generar(id);
            return View(result);
        }

        public ActionResult CalcularVacaciones()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CalcularVacaciones(DiasVacaciones diasVacaciones)
        {
            var vacaciones = _calcularVacaciones.Calcular(diasVacaciones.FechaInicio, diasVacaciones.FechaFin);
            ViewBag.Message = vacaciones;
            return View();
        }

        public ActionResult RegistrarVacaciones()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegistrarVacaciones(int id, Vacaciones vacaciones)
        {
            var resut = _registrarVacaciones.Registrar(id, vacaciones.FechaInicio, vacaciones.FechaFin);
            return RedirectToAction(nameof(Index));
        }
    }
}

Invercasa.Web/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Invercasa.Web.Controllers
{
    public class ErrorController : Controller
    {
        [Route("Error/{statusCode}")]
        public IActionResult HttpStatusCodeHandler(int statusCode)
        {
            switch (statusCode)
            {
                case 404: ViewBag.errorMessage = "Page Not Found"; 
                    break;
            }
            return View("NotFound");
        }
    }
}

Invercasa.Web/Views/Empleado/CalcularVacaciones.cshtml
@model Invercasa.Web.Models.DiasVacaciones

@{
    ViewData["Title"] = "CalcularVacaciones";
}

<link href=~/css/CalendarioVacaciones.css rel="stylesheet" type="text/css" />
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<h4>Calcular Vacaciones</h4>

<hr />

<div class="posision">
    <div>
        <form asp-action="CalcularVacaciones">
            <div class="d-flex justify-content-around">

                <div class="form-group">
                    <label asp-for="FechaInicio" class="control-label"></label>
                    <input asp-for="FechaInicio" class="form-control" />
                    <span asp-validation-for="FechaInicio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaFin" class="control-label"></label>
                    <input asp-for="FechaFin" class="form-control" />
                    <span asp-validation-for="FechaFin" class="text-danger"></span>
                </div>

            </div>

            <br />
            <br />

            <div class="d-flex justify-content-center">
                <div class="form-group">
                    <input type="submit" value="Calcular" class="btn btn-success" />
                </div>
            </div>

        </form>
    </div>
</div>

<br />
<br />

<div>
    <a asp-action="Index" class="btn btn-primary">Volver a la lista</a>
</div>


@section Scripts {
@{
await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

@if (ViewBag.Message != null)
{
    <script>
        Swal.fire(
            '@ViewBag.Message días de vacaciones');
    </script>
}

Invercasa.Web/Views/Empleado/CrearEmpleado.cshtml
@model Invercasa.Dominio.Entidades.Empleado

@{
    ViewData["Title"] = "CrearEmpleado";
}

<link href=~/css/CalendarioVacaciones.css rel="stylesheet" type="text/css" />
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<h4>Crear Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4 centrar">
        <form asp-action="CrearEmpleado">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoIdentificacion" class="control-label"></label>
                <input asp-for="TipoIdentificacion" class="form-control" />
                <span asp-validation-for="TipoIdentificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroIdentificacion" class="control-label"></label>
                <input asp-for="NumeroIdentificacion" class="form-control" />
                <span asp-validation-for="NumeroIdentificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" />
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalarioBaseMensual" class="control-label"></label>
                <input asp-for="SalarioBaseMensual" class="form-control" />
                <span asp-validation-for="SalarioBaseMensual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <hr />
            <br />
            <div class="d-flex justify-content-center">
                <div>
                    <input type="submit" value="Crear Empleado" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
</div>

<br />
<br />
<div>
    <a asp-action="Index" class="btn btn-primary">Volver a la lista</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

@if (ViewBag.Message != null)
{
    <script>
        Swal.fire(
            'El número de identificacion @ViewBag.Message ya existe!');
    </script>
}

Invercasa.Web/Views/Empleado/Index.cshtml
@model IEnumerable<Invercasa.Dominio.Entidades.Empleado>

@{
    ViewData["Title"] = "Index";
}
<h4>Lista de Empleado</h4>
<link href=~/css/CalendarioVacaciones.css rel="stylesheet" type="text/css" />

<div class="linea">
    <p>
        <a asp-action="CrearEmpleado" class="btn btn-success">Nuevo Empleado</a>
    </p>
    
    <p>
        <a asp-action="CalcularVacaciones" class="btn btn-primary">Calcular Vacaciones</a>
    </p>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoIdentificacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroIdentificacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaIngreso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SalarioBaseMensual)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>
            @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.TipoIdentificacion)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.NumeroIdentificacion)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.FechaIngreso)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.SalarioBaseMensual)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
            @Html.ActionLink("Reporte", "Reporte", new {  id=item.Id  }, new { @class = "btn btn-outline-secondary" })
            @Html.ActionLink("Vacaciones", "RegistrarVacaciones", new {  id=item.Id  }, new { @class = "btn btn-outline-secondary" })
            </td>
            </tr>
            }
    </tbody>
</table>

Invercasa.Web/Views/Empleado/RegistrarVacaciones.cshtml
@model Invercasa.Dominio.Entidades.Vacaciones

@{
    ViewData["Title"] = "RegistrarVacaciones";
}

<link href=~/css/CalendarioVacaciones.css rel="stylesheet" type="text/css" />

<h4>Registrar Vacaciones</h4>
<hr />

<div class="row">
    <div class="col-md-4 centrar">
        <form asp-action="RegistrarVacaciones">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="IdEmpleado" />

            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFin" class="control-label"></label>
                <input asp-for="FechaFin" class="form-control" />
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>

            <hr />
            <br />

            <div class="form-group d-flex justify-content-center">
                <input type="submit" value="Registrar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<br />
<br />

<div>
    <a asp-action="Index" class="btn btn-primary">Volver a la lista</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Invercasa.Web/Views/Empleado/Reporte.cshtml
@*@model IEnumerable<Invercasa.Servicios.Modelos.Reporte>*@
@model Invercasa.Servicios.Modelos.Reporte

@{
    ViewData["Title"] = "Reportes";
}

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdEmpleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaIngreso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiasTomados)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiasGenerados)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Saldos)
            </th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <td>
            @Html.DisplayFor(model => model.IdEmpleado)
            </td>
            <td>
            @Html.DisplayFor(model => model.Nombre)
            </td>
            <td>
            @Html.DisplayFor(model => model.FechaIngreso)
            </td>
            <td>
            @Html.DisplayFor(model => model.DiasTomados)
            </td>
            <td>
            @Html.DisplayFor(model => model.DiasGenerados)
            </td>
            <td>
            @Html.DisplayFor(model => model.Saldos)
            </td>
    </tbody>
</table>

<br />
<br />
<div>
    <a asp-action="Index" class="btn btn-primary">Volver a la lista</a>
</div>

Invercasa.Web/Views/Shared/NotFound.cshtml
<h3>No Encontrado</h3>

<p>El recurso buscado no ha podido ser encontrado.
    <a asp-controller="Empleado" asp-action="Index">Click aqui</a> para regresar.
    </p>

Invercasa.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Invercasa</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Invercasa.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Invercasa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="Index">Empleado</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Invercasa.Web - <a asp-area="" asp-controller="Empleado" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>